[build]
  # Path to your frontend build output
  publish = "dist" # or "build", depending on your React setup
  # Path to your Netlify Functions
  functions = "netlify/functions"

[functions]
  # Optional: Use esbuild for modern bundling
  node_bundler = "esbuild"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200